export const SET_LIWING_WAGES_ID = "SET_LIWING_WAGES_ID";

//load social groups
export const FETCH_SOCIAL_GROUP_REQUESTED = "FETCH_SOCIAL_GROUP_REQUESTED";
export const FETCH_SOCIAL_GROUP_SUCCESS = "FETCH_SOCIAL_GROUP_SUCCESS";
export const FETCH_SOCIAL_GROUP_FAILURE = "FETCH_SOCIAL_GROUP_FAILURE";

//load livingWages data
export const FETCH_LIVING_WAGES_REQUESTED = "FETCH_LIVING_WAGES_REQUESTED";
export const FETCH_LIVING_WAGES_SUCCESS = "FETCH_LIVING_WAGES_SUCCESS";
export const FETCH_LIVING_WAGES_FAILURE = "FETCH_LIVING_WAGES_FAILURE";

//Added item livingWages data
export const LIVING_WAGES_ADD_REQUESTED = "LIVING_WAGES_ADD_REQUESTED";
export const LIVING_WAGES_ADD_SUCCESS = "LIVING_WAGES_ADD_SUCCESS";
export const LIVING_WAGES_ADD_FAILURE = "LIVING_WAGES_ADD_FAILURE";

//Deleted item livingWages data
export const LIVING_WAGES_DEL_REQUESTED = "LIVING_WAGES_DEL_REQUESTED";
export const LIVING_WAGES_DEL_SUCCESS = "LIVING_WAGES_DEL_SUCCESS";
export const LIVING_WAGES_DEL_FAILURE = "LIVING_WAGES_DEL_FAILURE";