//_______________________LIVINGWAGES_________________________

export const SET_LIWING_WAGES_ID = "SET_LIWING_WAGES_ID";

//load social groups
export const FETCH_SOCIAL_GROUP_REQUESTED = "FETCH_SOCIAL_GROUP_REQUESTED";
export const FETCH_SOCIAL_GROUP_SUCCESS = "FETCH_SOCIAL_GROUP_SUCCESS";
export const FETCH_SOCIAL_GROUP_FAILURE = "FETCH_SOCIAL_GROUP_FAILURE";

//load livingWages data
export const FETCH_LIVING_WAGES_REQUESTED = "FETCH_LIVING_WAGES_REQUESTED";
export const FETCH_LIVING_WAGES_SUCCESS = "FETCH_LIVING_WAGES_SUCCESS";
export const FETCH_LIVING_WAGES_FAILURE = "FETCH_LIVING_WAGES_FAILURE";

//Addition item livingWages data
export const LIVING_WAGES_ADD_REQUESTED = "LIVING_WAGES_ADD_REQUESTED";
export const LIVING_WAGES_ADD_SUCCESS = "LIVING_WAGES_ADD_SUCCESS";
export const LIVING_WAGES_ADD_FAILURE = "LIVING_WAGES_ADD_FAILURE";

//Deleted item livingWages data
export const LIVING_WAGES_DEL_REQUESTED = "LIVING_WAGES_DEL_REQUESTED";
export const LIVING_WAGES_DEL_SUCCESS = "LIVING_WAGES_DEL_SUCCESS";
export const LIVING_WAGES_DEL_FAILURE = "LIVING_WAGES_DEL_FAILURE";



//_______________________ADDRESSES_________________________

//load adresses of Regions
export const FETCH_ADDRESSES_REGIONS_REQUESTED = "FETCH_ADDRESSES_REGIONS_REQUESTED";
export const FETCH_ADDRESSES_REGIONS_SUCCESS = "FETCH_ADDRESSES_REGIONS_SUCCESS";
export const FETCH_ADDRESSES_REGIONS_FAILURE = "FETCH_ADDRESSES_REGIONS_FAILURE";

//load adresses of childs
export const FETCH_ADDRESSES_CHILDS_REQUESTED = "FETCH_ADDRESSES_CHILDS_REQUESTED";
export const FETCH_ADDRESSES_CHILDS_SUCCESS = "FETCH_ADDRESSES_CHILDS_SUCCESS";
export const FETCH_ADDRESSES_CHILDS_FAILURE = "FETCH_ADDRESSES_CHILDS_FAILURE";

//Addeting item in child 
export const ADDETING_ADDRESSES_CHILDS_REQUESTED = "ADDETING_ADDRESSES_CHILDS_REQUESTED";
export const ADDETING_ADDRESSES_CHILDS_SUCCESS = "ADDETING_ADDRESSES_CHILDS_SUCCESS";
export const ADDETING_ADDRESSES_CHILDS_FAILURE = "ADDETING_ADDRESSES_CHILDS_FAILURE";

//Editing item in child
export const EDITING_ADDRESSES_CHILDS_REQUESTED = "EDITING_ADDRESSES_CHILDS_REQUESTED";
export const EDITING_ADDRESSES_CHILDS_SUCCESS = "EDITING_ADDRESSES_CHILDS_SUCCESS";
export const EDITING_ADDRESSES_CHILDS_FAILURE = "EDITING_ADDRESSES_CHILDS_FAILURE";

//Delete child
export const DELETE_ADDRESSES_CHILDS_REQUESTED = "DELETE_ADDRESSES_CHILDS_REQUESTED";
export const DELETE_ADDRESSES_CHILDS_SUCCESS = "DELETE_ADDRESSES_CHILDS_SUCCESS";
export const DELETE_ADDRESSES_CHILDS_FAILURE = "DELETE_ADDRESSES_CHILDS_FAILURE";



//_______________________ORGSTRUCTURES_________________________

//load orginits
export const FETCH_ORGUNITS_REQUESTED = "FETCH_ORGUNITS_REQUESTED";
export const FETCH_ORGUNITS_SUCCESS = "FETCH_ORGUNITS_SUCCESS";
export const FETCH_ORGUNITS_FAILURE = "FETCH_ORGUNITS_FAILURE";

//load organizational structure
export const FETCH_ORGSTRUCTURES_REQUESTED = "FETCH_ORGSTRUCTURES_REQUESTED";
export const FETCH_ORGSTRUCTURES_SUCCESS = "FETCH_ORGSTRUCTURES_SUCCESS";
export const FETCH_ORGSTRUCTURES_FAILURE = "FETCH_ORGSTRUCTURES_FAILURE";

//Addeting item in organizational structure 
export const ADDETING_ORGSTRUCTURES_REQUESTED = "ADDETING_ORGSTRUCTURES_REQUESTED";
export const ADDETING_ORGSTRUCTURES_SUCCESS = "ADDETING_ORGSTRUCTURES_SUCCESS";
export const ADDETING_ORGSTRUCTURES_FAILURE = "ADDETING_ORGSTRUCTURES_FAILURE";

//Editing item in organizational structure 
export const EDITING_ORGSTRUCTURES_REQUESTED = "EDITING_ORGSTRUCTURES_REQUESTED";
export const EDITING_ORGSTRUCTURES_SUCCESS = "EDITING_ORGSTRUCTURES_SUCCESS";
export const EDITING_ORGSTRUCTURES_FAILURE = "EDITING_ORGSTRUCTURES_FAILURE";

//Delete organizational structure
export const DELETE_ORGSTRUCTURES_REQUESTED = "DELETE_ORGSTRUCTURES_REQUESTED";
export const DELETE_ORGSTRUCTURES_SUCCESS = "DELETE_ORGSTRUCTURES_SUCCESS";
export const DELETE_ORGSTRUCTURES_FAILURE = "DELETE_ORGSTRUCTURES_FAILURE";



//_______________________JOBPOSITIONS_________________________

//load jobpositions
export const FETCH_JOBPOSITIONS_REQUESTED = "FETCH_JOBPOSITIONS_REQUESTED";
export const FETCH_JOBPOSITIONS_SUCCESS = "FETCH_JOBPOSITIONS_SUCCESS";
export const FETCH_JOBPOSITIONS_FAILURE = "FETCH_JOBPOSITIONS_FAILURE";

//Addeting item in jobposition
export const ADDETING_JOBPOSITIONS_REQUESTED = "ADDETING_JOBPOSITIONS_REQUESTED";
export const ADDETING_JOBPOSITIONS_SUCCESS = "ADDETING_JOBPOSITIONS_SUCCESS";
export const ADDETING_JOBPOSITIONS_FAILURE = "ADDETING_JOBPOSITIONS_FAILURE";

//Editing item in jobposition
export const EDITING_JOBPOSITIONS_REQUESTED = "EDITING_JOBPOSITIONS_REQUESTED";
export const EDITING_JOBPOSITIONS_SUCCESS = "EDITING_JOBPOSITIONS_SUCCESS";
export const EDITING_JOBPOSITIONS_FAILURE = "EDITING_JOBPOSITIONS_FAILURE";

//Delete organizational jobposition
export const DELETE_JOBPOSITIONS_REQUESTED = "DELETE_JOBPOSITIONS_REQUESTED";
export const DELETE_JOBPOSITIONS_SUCCESS = "DELETE_JOBPOSITIONS_SUCCESS";
export const DELETE_JOBPOSITIONS_FAILURE = "DELETE_JOBPOSITIONS_FAILURE";



//_______________________ROLES_________________________

//load roles
export const FETCH_ROLES_REQUESTED = "FETCH_ROLES_REQUESTED";
export const FETCH_ROLES_SUCCESS = "FETCH_ROLES_SUCCESS";
export const FETCH_ROLES_FAILURE = "FETCH_ROLES_FAILURE";

//Addeting item in role
export const ADDETING_ROLES_REQUESTED = "ADDETING_ROLES_REQUESTED";
export const ADDETING_ROLES_SUCCESS = "ADDETING_ROLES_SUCCESS";
export const ADDETING_ROLES_FAILURE = "ADDETING_ROLES_FAILURE";

//Editing item in role
export const EDITING_ROLES_REQUESTED = "EDITING_ROLES_REQUESTED";
export const EDITING_ROLES_SUCCESS = "EDITING_ROLES_SUCCESS";
export const EDITING_ROLES_FAILURE = "EDITING_ROLES_FAILURE";

//Delete roles
export const DELETE_ROLES_REQUESTED = "DELETE_ROLES_REQUESTED";
export const DELETE_ROLES_SUCCESS = "DELETE_ROLES_SUCCESS";
export const DELETE_ROLES_FAILURE = "DELETE_ROLES_FAILURE";



//_______________________EMPLOYEES_________________________

//load employees
export const FETCH_EMPLOYEES_REQUESTED = "FETCH_EMPLOYEES_REQUESTED";
export const FETCH_EMPLOYEES_SUCCESS = "FETCH_EMPLOYEES_SUCCESS";
export const FETCH_EMPLOYEES_FAILURE = "FETCH_EMPLOYEES_FAILURE";

//Addeting item in employee
export const ADDETING_EMPLOYEES_REQUESTED = "ADDETING_EMPLOYEES_REQUESTED";
export const ADDETING_EMPLOYEES_SUCCESS = "ADDETING_EMPLOYEES_SUCCESS";
export const ADDETING_EMPLOYEES_FAILURE = "ADDETING_EMPLOYEES_FAILURE";

//Editing item in employee
export const EDITING_EMPLOYEES_REQUESTED = "EDITING_EMPLOYEES_REQUESTED";
export const EDITING_EMPLOYEES_SUCCESS = "EDITING_EMPLOYEES_SUCCESS";
export const EDITING_EMPLOYEES_FAILURE = "EDITING_EMPLOYEES_FAILURE";

//Delete employee
export const DELETE_EMPLOYEES_REQUESTED = "DELETE_EMPLOYEES_REQUESTED";
export const DELETE_EMPLOYEES_SUCCESS = "DELETE_EMPLOYEES_SUCCESS";
export const DELETE_EMPLOYEES_FAILURE = "DELETE_EMPLOYEES_FAILURE";



//_______________________RELATIONS_________________________

//load relations
export const FETCH_RELATIONS_REQUESTED = "FETCH_RELATIONS_REQUESTED";
export const FETCH_RELATIONS_SUCCESS = "FETCH_RELATIONS_SUCCESS";
export const FETCH_RELATIONS_FAILURE = "FETCH_RELATIONS_FAILURE";

//load relationdependences
export const FETCH_RELATIONDEPENDENCES_REQUESTED = "FETCH_RELATIONDEPENDENCES_REQUESTED";
export const FETCH_RELATIONDEPENDENCES_SUCCESS = "FETCH_RELATIONDEPENDENCES_SUCCESS";
export const FETCH_RELATIONDEPENDENCES_FAILURE = "FETCH_RELATIONDEPENDENCES_FAILURE";

//Addeting item in relationdependence
export const ADDETING_RELATIONDEPENDENCES_REQUESTED = "ADDETING_RELATIONDEPENDENCES_REQUESTED";
export const ADDETING_RELATIONDEPENDENCES_SUCCESS = "ADDETING_RELATIONDEPENDENCES_SUCCESS";
export const ADDETING_RELATIONDEPENDENCES_FAILURE = "ADDETING_RELATIONDEPENDENCES_FAILURE";

//Editing item in relationdependence
export const EDITING_RELATIONDEPENDENCES_REQUESTED = "EDITING_RELATIONDEPENDENCES_REQUESTED";
export const EDITING_RELATIONDEPENDENCES_SUCCESS = "EDITING_RELATIONDEPENDENCES_SUCCESS";
export const EDITING_RELATIONDEPENDENCES_FAILURE = "EDITING_RELATIONDEPENDENCES_FAILURE";

//Delete relation
export const DELETE_RELATIONS_REQUESTED = "DELETE_RELATIONS_REQUESTED";
export const DELETE_RELATIONS_SUCCESS = "DELETE_RELATIONS_SUCCESS";
export const DELETE_RELATIONS_FAILURE = "DELETE_RELATIONS_FAILURE";



//_______________________BANKS_________________________

//load banks
export const FETCH_BANKS_REQUESTED = "FETCH_BANKS_REQUESTED";
export const FETCH_BANKS_SUCCESS = "FETCH_BANKS_SUCCESS";
export const FETCH_BANKS_FAILURE = "FETCH_BANKS_FAILURE";

//Addeting item in bank
export const ADDETING_BANKS_REQUESTED = "ADDETING_BANKS_REQUESTED";
export const ADDETING_BANKS_SUCCESS = "ADDETING_BANKS_SUCCESS";
export const ADDETING_BANKS_FAILURE = "ADDETING_BANKS_FAILURE";

//Editing item in bank
export const EDITING_BANKS_REQUESTED = "EDITING_BANKS_REQUESTED";
export const EDITING_BANKS_SUCCESS = "EDITING_BANKS_SUCCESS";
export const EDITING_BANKS_FAILURE = "EDITING_BANKS_FAILURE";

//Delete bank
export const DELETE_BANKS_REQUESTED = "DELETE_BANKS_REQUESTED";
export const DELETE_BANKS_SUCCESS = "DELETE_BANKS_SUCCESS";
export const DELETE_BANKS_FAILURE = "DELETE_BANKS_FAILURE";



//_______________________MAXCOSTS_________________________

//load maxcosts
export const FETCH_MAXCOSTS_REQUESTED = "FETCH_MAXCOSTS_REQUESTED";
export const FETCH_MAXCOSTS_SUCCESS = "FETCH_MAXCOSTS_SUCCESS";
export const FETCH_MAXCOSTS_FAILURE = "FETCH_MAXCOSTS_FAILURE";

//Addeting item in maxcost
export const ADDETING_MAXCOSTS_REQUESTED = "ADDETING_MAXCOSTS_REQUESTED";
export const ADDETING_MAXCOSTS_SUCCESS = "ADDETING_MAXCOSTS_SUCCESS";
export const ADDETING_MAXCOSTS_FAILURE = "ADDETING_MAXCOSTS_FAILURE";

//Editing item in maxcost
export const EDITING_MAXCOSTS_REQUESTED = "EDITING_MAXCOSTS_REQUESTED";
export const EDITING_MAXCOSTS_SUCCESS = "EDITING_MAXCOSTS_SUCCESS";
export const EDITING_MAXCOSTS_FAILURE = "EDITING_MAXCOSTS_FAILURE";

//Delete maxcost
export const DELETE_MAXCOSTS_REQUESTED = "DELETE_MAXCOSTS_REQUESTED";
export const DELETE_MAXCOSTS_SUCCESS = "DELETE_MAXCOSTS_SUCCESS";
export const DELETE_MAXCOSTS_FAILURE = "DELETE_MAXCOSTS_FAILURE";