export const FETCH_SOCIAL_GROUP_REQUESTED = "FETCH_SOCIAL_GROUP_REQUESTED";
export const FETCH_SOCIAL_GROUP_SUCCESS = "FETCH_SOCIAL_GROUP_SUCCESS";
export const FETCH_SOCIAL_GROUP_FAILURE = "FETCH_SOCIAL_GROUP_FAILURE";
export const SET_SOCIAL_GROUP_ID = "SET_SOCIAL_GROUP_ID";

export const FETCH_LIVING_WAGES_REQUESTED = "FETCH_LIVING_WAGES_REQUESTED";
export const FETCH_LIVING_WAGES_SUCCESS = "FETCH_LIVING_WAGES_SUCCESS";
export const FETCH_LIVING_WAGES_FAILURE = "FETCH_LIVING_WAGES_FAILURE";
export const GET_LIVING_WAGES_LENGTH = "GET_LIVING_WAGES_LENGTH";
